(function(root){
  "use strict";
  const BUILD=Object.freeze({work_package:"FB-ARCH-01A",increment:"B8",component:"import_export_share_surface",version:"0.1.0-private",build:"1.8.1-dev.8+fb-arch-01a-b8"});
  const CORE_ACTIONS=Object.freeze(["share_fleet","export_fleet","import_fleet"]);
  const externalActions=new Map();
  let mounted=false,bound=false,renderCount=0,bindCount=0,lastReason="",controller=null,lastError=null;
  function doc(){return root.document||null;}
  function io(){return root.MowFleetIO||null;}
  function library(){return root.MOW_FLEET_LIBRARY||null;}
  function ensureServices(){const I=io(),L=library();if(!I||typeof I.prepareCentralSurface!=="function")throw new Error("Central portable IO service is unavailable.");if(!L||typeof L.prepareCentralImportExportShare!=="function")throw new Error("Central library share/backup service is unavailable.");return {I,L};}
  function actionBar(){return doc()?.querySelector?.("#mowFleetActionsBar .mow-fleet-actions-main")||null;}
  function renderExternalActions(){const bar=actionBar();if(!bar)return;bar.querySelectorAll("[data-fbarch-io-action]").forEach(el=>el.remove());const help=doc()?.getElementById?.("mowOpenHelp")||null;Array.from(externalActions.values()).sort((a,b)=>(a.order||500)-(b.order||500)||a.id.localeCompare(b.id)).forEach(action=>{const button=doc().createElement("button");button.type="button";button.dataset.fbarchIoAction=action.id;button.textContent=typeof action.label==="function"?String(action.label()):String(action.label||action.id);bar.insertBefore(button,help||null);});}
  function render(_projection,options){const {I,L}=ensureServices();I.prepareCentralSurface();L.prepareCentralImportExportShare();I.refreshCentralSurface();L.refreshCentralImportExportShare();renderExternalActions();mounted=true;renderCount+=1;lastReason=String(options&&options.reason||"");return status();}
  async function onClick(event){try{const target=event?.target?.closest?.("button,[data-portable-close],[data-open-fleet-setup],[data-fbarch-io-action],#mowShareFleetLink");if(!target)return;const I=io(),L=library();if(target.id==="mowPortableExportButton"){I.openCentralExport();return;}if(target.id==="mowPortableImportButton"){I.openCentralImport();return;}if(target.id==="mowPortableDownload"){I.downloadCentralExport();return;}if(target.id==="mowPortableCheckImport"){I.checkCentralImport();return;}if(target.id==="mowPortableChooseFile"){I.chooseCentralImportFile();return;}if(target.id==="mowPortableApplyImport"){await I.applyCentralImport();return;}if(target.matches?.("[data-portable-close]")){I.closeCentralModal(target.dataset.portableClose);return;}if(target.matches?.("[data-open-fleet-setup]")){I.openCentralFleetSetup();return;}if(target.id==="mowShareFleet"){await L.shareCurrentFleet();return;}if(target.id==="mowCopyFleetLink"){await L.copyCentralShareLink();return;}if(target.id==="mowShareFleetLink"){L.selectCentralShareLink();return;}if(target.id==="mowExportFleetLibrary"){L.exportLibraryBackup();return;}if(target.id==="mowImportFleetLibrary"){L.chooseLibraryImportFile();return;}if(target.id==="mowFleetImportMerge"){await L.applyLibraryImportCandidate("merge");return;}if(target.id==="mowFleetImportReplace"){await L.applyLibraryImportCandidate("replace");return;}const actionId=target.dataset?.fbarchIoAction;if(actionId&&externalActions.has(actionId)){const action=externalActions.get(actionId);await action.invoke({controller,projection:controller?.currentProjection?.()||null,library:L,io:I,button:target});return;}}catch(error){lastError=String(error&&error.message||error);console.error(error);}}
  async function onChange(event){try{const target=event?.target;if(!target)return;const I=io(),L=library();if(target.id==="mowPortableProfile"){I.refreshCentralExport();return;}if(target.id==="mowPortableFleetFile"){const file=target.files&&target.files[0];target.value="";if(file)await I.handleCentralImportFile(file);return;}if(target.id==="mowFleetLibraryFile"){const file=target.files&&target.files[0];target.value="";if(file)await L.handleLibraryImportFile(file);return;}}catch(error){lastError=String(error&&error.message||error);console.error(error);}}
  function bind(context){if(bound)return status();const d=doc();if(!d)throw new Error("Central import/export/share surface requires document.");controller=context&&context.controller||null;d.addEventListener("click",onClick,false);d.addEventListener("change",onChange,false);bound=true;bindCount+=1;return status();}
  function registerAction(definition){const def=definition||{},id=String(def.id||"").trim();if(!id)throw new Error("Action id is required.");if(CORE_ACTIONS.includes(id))throw new Error(`Reserved core action id '${id}'.`);if(externalActions.has(id))throw new Error(`Action '${id}' is already registered.`);if(typeof def.invoke!=="function")throw new Error(`Action '${id}' requires invoke().`);const record=Object.freeze({id,label:def.label||id,order:Number.isFinite(Number(def.order))?Number(def.order):500,invoke:def.invoke,owner:String(def.owner||"external")});externalActions.set(id,record);if(mounted)renderExternalActions();return record;}
  function actionRegistry(){return Object.freeze({schema:"mow.builder.action_registry",schema_version:"0.1.0-private",core_actions:CORE_ACTIONS.slice(),external_actions:Array.from(externalActions.values()).map(x=>({id:x.id,order:x.order,owner:x.owner})),integration_point:"MowImportExportShareSurface.registerAction"});}
  function status(){const d=doc(),I=io(),L=library(),is=I?.centralStatus?.()||{},ls=L?.centralImportExportShareStatus?.()||{};return Object.freeze({build:BUILD,mounted,bound,render_count:renderCount,bind_count:bindCount,last_reason:lastReason,last_error:lastError,action_bar:!!actionBar(),share_button_count:d?.querySelectorAll?.("#mowShareFleet")?.length||0,export_button_count:d?.querySelectorAll?.("#mowPortableExportButton")?.length||0,import_button_count:d?.querySelectorAll?.("#mowPortableImportButton")?.length||0,portable_export_modal_count:d?.querySelectorAll?.("#mowPortableExportModal")?.length||0,portable_import_modal_count:d?.querySelectorAll?.("#mowPortableImportModal")?.length||0,share_modal_count:d?.querySelectorAll?.("#mowShareFleetModal")?.length||0,legacy_portable_io_autonomous:is.autonomous!==false,legacy_library_io_share_autonomous:ls.autonomous!==false,registry:actionRegistry()});}
  const api=Object.freeze({BUILD,render,bind,status,registerAction,actionRegistry});
  root.MowImportExportShareSurface=api;root.MOW_FB_ARCH_01A_IMPORT_EXPORT_SHARE_SURFACE=api;if(typeof module!=="undefined"&&module.exports)module.exports=api;
})(typeof window!=="undefined"?window:globalThis);
